{
 "title": "Capacity Planning",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Instances by State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance_state) (nova_instances{cloud=\"orange\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Current Top 10 Courses",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (count by (course_name) (nova_instances_metadata{cloud=\"orange\"})))",
     "legendFormat": "{{course_name}}"
    }
   ]
  },
  {
   "title": "Current Top 10 agnosticD Configs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (count by (env_type) (nova_instances_metadata{cloud=\"orange\"})))",
     "legendFormat": "{{env_type}}"
    }
   ]
  },
  {
   "title": "7-Day Maximum Instances per Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(hypervisor_running_vms{cloud=\"orange\",nova_service_status=\"enabled\"}[7d])",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "30-Day Maximum Instances per Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max_over_time(hypervisor_running_vms{cloud=\"orange\",nova_service_status=\"enabled\"}[30d])",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "7-Day Maximum vCPUs per Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(hypervisor_vcpus_used{cloud=\"orange\",nova_service_status=\"enabled\"}[7d])",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "30-Day Maximum vCPUs per Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(hypervisor_vcpus_used{cloud=\"orange\",nova_service_status=\"enabled\"}[30d])",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "7-Day Maximum RAM usage per Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(hypervisor_memory_mbs_used{cloud=\"orange\",nova_service_status=\"enabled\"}[7d])",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "30-Day Maximum RAM usage per Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(hypervisor_memory_mbs_used{cloud=\"orange\",nova_service_status=\"enabled\"}[30d])",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hypervisor_memory_mbs_used{cloud=\"orange\",nova_service_status=\"enabled\"} / hypervisor_memory_mbs_total{cloud=\"orange\",nova_service_status=\"enabled\"}",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Hypervisor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hypervisor_memory_mbs_used{cloud=\"orange\",nova_service_status=\"enabled\"} / hypervisor_memory_mbs_total{cloud=\"orange\",nova_service_status=\"enabled\"}",
     "legendFormat": "{{hypervisor_hostname}}"
    }
   ]
  },
  {
   "title": "Neutron Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(neutron_net_size{cloud=\"orange\"})"
    }
   ]
  }
 ]
}