{
 "title": "Capacity Planning",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Current Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances by State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance_state) (nova_instances{cloud=\"orange\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Neutron Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(neutron_net_size{cloud=\"orange\"})"
    }
   ]
  },
  {
   "title": "Current Top 10 Courses",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (count by (course_name) (nova_instances_metadata{cloud=\"orange\"})))",
     "legendFormat": "{{course_name}}"
    }
   ]
  },
  {
   "title": "Current Top 10 agnosticD Configs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (count by (env_type) (nova_instances_metadata{cloud=\"orange\"})))",
     "legendFormat": "{{env_type}}"
    }
   ]
  },
  {
   "title": "Top-10 vCPU consumers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by (tenant) (nova_resources_vcpus{cloud=\"orange\"})))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top-10 RAM consumers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by (tenant) (nova_resources_ram_mbs{cloud=\"orange\"}/1024)))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top-10 Public IP consumers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by (tenant) (neutron_public_ip_usage{cloud=\"orange\"})))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top-10 Disk (GB) consumers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10, (sum by (tenant) (nova_resources_disk_gbs{cloud=\"orange\"})))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Hypervisor Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true
  },
  {
   "title": "7-Day Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "7-Day Maximum Instances per Hypervisor",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max_over_time(hypervisor_running_vms{cloud=\"orange\",nova_service_status=\"enabled\"}[7d])",
       "legendFormat": "{{hypervisor_hostname}}"
      }
     ]
    },
    {
     "title": "7-Day Maximum vCPUs per Hypervisor",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max_over_time(hypervisor_vcpus_used{cloud=\"orange\",nova_service_status=\"enabled\"}[7d])",
       "legendFormat": "{{hypervisor_hostname}}"
      }
     ]
    },
    {
     "title": "7-Day Maximum RAM usage per Hypervisor",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max_over_time(hypervisor_memory_mbs_used{cloud=\"orange\",nova_service_status=\"enabled\"}[7d])",
       "legendFormat": "{{hypervisor_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "30-Day Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "30-Day Maximum Instances per Hypervisor",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max_over_time(hypervisor_running_vms{cloud=\"orange\",nova_service_status=\"enabled\"}[30d])",
       "legendFormat": "{{hypervisor_hostname}}"
      }
     ]
    },
    {
     "title": "30-Day Maximum vCPUs per Hypervisor",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max_over_time(hypervisor_vcpus_used{cloud=\"orange\",nova_service_status=\"enabled\"}[30d])",
       "legendFormat": "{{hypervisor_hostname}}"
      }
     ]
    },
    {
     "title": "30-Day Maximum RAM usage per Hypervisor",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max_over_time(hypervisor_memory_mbs_used{cloud=\"orange\",nova_service_status=\"enabled\"}[30d])",
       "legendFormat": "{{hypervisor_hostname}}"
      }
     ]
    }
   ]
  }
 ]
}